apiVersion: v1
kind: Service
metadata:
  name: ocr-service
spec:
  type: NodePort
  selector:
    app: ocr
  ports:
  - port: 8080  # Service port exposed to the cluster
    targetPort: 80  # Container port to forward traffic to
    nodePort: 30080  # Optional: Specify a specific NodePort (if not set, Kubernetes will assign one)

